# GET http://localhost:4000/api/movies

# GET http://localhost:4000/api/movies/62faca5ed33ff9933c99d5f9

# GET http://localhost:4000/api/movies/category/action

# POST http://localhost:4000/api/movies

# Content-Type: application/json

# {
#  "name":"levers",
#  "category":"romance",
#  "author":"juan luis",
#  "describtion":"this movie is about a person call jennifer aniston",
#  "new":true
# }

# PUT http://localhost:4000/api/movies/update/62faca5ed33ff9933c99d5f9
# Content-Type: application/json

# {
#  "name":"iron",
#  "category":"action",
#  "author":"juan carlos",
#  "describtion":"this movie is about a person call iron",
#  "new":true
# }

 DELETE http://localhost:4000/api/movies/delete/